#!/usr/bin/env bash
set -euo pipefail

MODULE_DIR="${1:-}"
RESOURCE_RAW="${2:-}"
FORCE=0

shift $(( $# >= 2 ? 2 : $# )) || true
for arg in "$@"; do
  case "$arg" in
    --force) FORCE=1 ;;
    --provider|--api)
      echo "$arg is intentionally not generated by this script."
      echo "Write Provider/Service/API manually only after reading references/service-api.md."
      exit 1
      ;;
    *) echo "Unknown option: $arg"; exit 1 ;;
  esac
done

if [[ -z "$MODULE_DIR" || -z "$RESOURCE_RAW" ]]; then
  echo "Usage: bash scripts/module.sh <module_dir> <resource_name> [--force]"
  echo "This script only creates a model skeleton. It never creates Provider/API/Service."
  exit 1
fi

if [[ ! "$MODULE_DIR" =~ ^[A-Za-z0-9_-]+$ || ! "$RESOURCE_RAW" =~ ^[A-Za-z0-9_-]+$ ]]; then
  echo "module_dir and resource_name only support letters, numbers, underscore and hyphen."
  exit 1
fi

if [[ ! -f go.mod ]]; then
  echo "go.mod not found. Run this from project root."
  exit 1
fi

to_pascal() {
  echo "$1" | tr '-_' ' ' | awk '{for(i=1;i<=NF;i++){$i=toupper(substr($i,1,1)) tolower(substr($i,2))} printf "%s",$0}' | tr -d ' '
}

RESOURCE_FILE="$(echo "$RESOURCE_RAW" | tr '[:upper:]' '[:lower:]' | tr '-' '_')"
TYPE_NAME="$(to_pascal "$RESOURCE_FILE")"
MODEL_FUNC="New${TYPE_NAME}Model"
TABLE_NAME="${MODULE_DIR}_${RESOURCE_FILE}"
TARGET_FILE="module/${MODULE_DIR}/model/${RESOURCE_FILE}.go"

if [[ -e "$TARGET_FILE" && "$FORCE" != "1" ]]; then
  echo "Refuse to overwrite existing file: $TARGET_FILE"
  echo "Re-run with --force only after confirming replacement."
  exit 1
fi
if [[ -e "$TARGET_FILE" && "$FORCE" == "1" ]]; then
  cp "$TARGET_FILE" "${TARGET_FILE}.bak"
fi

mkdir -p "module/${MODULE_DIR}/model"

cat > "$TARGET_FILE" <<EOF
package model

import (
	"time"

	"github.com/shemic/dever/orm"
)

type ${TYPE_NAME} struct {
	ID        uint64    \`dorm:"primaryKey;autoIncrement;comment:主键ID"\`
	Name      string    \`dorm:"type:varchar(128);not null;comment:名称"\`
	Code      string    \`dorm:"type:varchar(128);not null;comment:标识"\`
	Status    int16     \`dorm:"type:smallint;not null;default:1;comment:状态"\`
	Sort      int       \`dorm:"type:int;not null;default:100;comment:排序"\`
	CreatedAt time.Time \`dorm:"comment:创建时间"\`
}

type ${TYPE_NAME}Index struct {
	Code       struct{} \`unique:"code"\`
	StatusSort struct{} \`index:"status,sort,id"\`
}

var ${RESOURCE_FILE}StatusOptions = []map[string]any{
	{"id": 1, "value": "启用"},
	{"id": 2, "value": "停用"},
}

func ${MODEL_FUNC}() *orm.Model[${TYPE_NAME}] {
	return orm.LoadModel[${TYPE_NAME}]("${TYPE_NAME}", "${TABLE_NAME}", orm.ModelConfig{
		Index:    ${TYPE_NAME}Index{},
		Order:    "sort asc,id asc",
		Database: "default",
		Options: map[string]any{
			"status": ${RESOURCE_FILE}StatusOptions,
		},
	})
}
EOF

echo "Generated:"
echo "  $TARGET_FILE"
echo "Provider/API/Service were not generated. Add them manually only for real business logic."
