package cmd

import (
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/shemic/dever/util"
)

type componentEntry struct {
	Name        string
	Source      string
	ImportPath  string
	ImportAlias string
	DiskDir     string
	ManifestFS  bool
	PageFS      bool
	FrontFS     bool
	PagePrefix  string
	FrontPrefix string
}

// GenerateComponents 扫描 active module/package，生成 component 资源注册文件。
func GenerateComponents(projectRoot string) error {
	sources, err := LoadProjectSources(projectRoot)
	if err != nil {
		return err
	}
	return GenerateComponentsForSources(sources)
}

func GenerateComponentsForSources(sources ProjectSources) error {
	importAliases := make(map[string]string)
	aliasUsage := make(map[string]int)
	entries := make([]componentEntry, 0, len(sources.ModuleSources))
	for _, source := range sources.ModuleSources {
		entry, ok := buildComponentEntry(sources.Root, source, importAliases, aliasUsage)
		if ok {
			entries = append(entries, entry)
		}
	}

	sort.SliceStable(entries, func(i, j int) bool {
		return entries[i].Name < entries[j].Name
	})

	output := filepath.Join(sources.Root, "data", "load", "component.go")
	code, err := buildComponentFile(entries, importAliases)
	if err != nil {
		return err
	}

	if err := os.MkdirAll(filepath.Dir(output), 0o755); err != nil {
		return fmt.Errorf("创建 data/load 目录失败: %w", err)
	}
	if err := os.WriteFile(output, []byte(code), 0o644); err != nil {
		return fmt.Errorf("写入 component.go 失败: %w", err)
	}

	if len(entries) == 0 {
		fmt.Println("⚠️ 未检测到 component manifest，已生成空的 data/load/component.go")
	} else {
		fmt.Println("✅ Components generated successfully → " + output)
	}
	return nil
}

func buildComponentEntry(rootPath string, source util.ModuleSource, importAliases map[string]string, aliasUsage map[string]int) (componentEntry, bool) {
	manifestPath := filepath.Join(source.Root, "dever.json")
	if _, err := os.Stat(manifestPath); err != nil {
		return componentEntry{}, false
	}

	resourceVars := componentResourceVars(source.Root)
	alias := ensureAlias(importAliases, aliasUsage, source.Import, filepath.Join(source.Name, "component"))
	entry := componentEntry{
		Name:        sanitizePathSegment(source.Name),
		Source:      componentSource(rootPath, source),
		ImportPath:  source.Import,
		ImportAlias: alias,
		DiskDir:     componentDiskDir(rootPath, source.Root),
		ManifestFS:  resourceVars["ManifestFS"],
		PageFS:      resourceVars["PageFS"],
		FrontFS:     resourceVars["FrontFS"],
		PagePrefix:  "front/page",
		FrontPrefix: "front/dist",
	}
	return entry, entry.ManifestFS
}

func componentSource(rootPath string, source util.ModuleSource) string {
	switch source.Kind {
	case util.ModuleSourceKindPackage:
		return util.ModuleSourceKindPackage
	case util.ModuleSourceKindModule:
		return util.ModuleSourceKindModule
	}

	packageRoot := filepath.Join(rootPath, "package") + string(os.PathSeparator)
	if strings.HasPrefix(source.Root+string(os.PathSeparator), packageRoot) {
		return util.ModuleSourceKindPackage
	}
	return util.ModuleSourceKindModule
}

func componentDiskDir(rootPath, target string) string {
	if !isInsideRoot(rootPath, target) {
		abs, err := filepath.Abs(target)
		if err != nil {
			return filepath.ToSlash(target)
		}
		return filepath.ToSlash(abs)
	}

	rel, err := filepath.Rel(rootPath, target)
	if err != nil {
		return filepath.ToSlash(target)
	}
	return filepath.ToSlash(rel)
}

func isInsideRoot(rootPath, target string) bool {
	root, err := filepath.Abs(rootPath)
	if err != nil {
		return false
	}
	targetPath, err := filepath.Abs(target)
	if err != nil {
		return false
	}
	rel, err := filepath.Rel(root, targetPath)
	if err != nil {
		return false
	}
	return rel == "." || (!strings.HasPrefix(rel, ".."+string(os.PathSeparator)) && rel != "..")
}

func componentResourceVars(rootPath string) map[string]bool {
	result := map[string]bool{}
	entries, err := os.ReadDir(rootPath)
	if err != nil {
		return result
	}

	names := map[string]struct{}{
		"ManifestFS": {},
		"PageFS":     {},
		"FrontFS":    {},
	}
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") || strings.HasSuffix(entry.Name(), "_test.go") {
			continue
		}

		file, err := parser.ParseFile(token.NewFileSet(), filepath.Join(rootPath, entry.Name()), nil, 0)
		if err != nil {
			continue
		}
		for _, decl := range file.Decls {
			current, ok := decl.(*ast.GenDecl)
			if !ok || current.Tok != token.VAR {
				continue
			}
			for _, spec := range current.Specs {
				values, ok := spec.(*ast.ValueSpec)
				if !ok {
					continue
				}
				for _, ident := range values.Names {
					if _, ok := names[ident.Name]; ok {
						result[ident.Name] = true
					}
				}
			}
		}
		if len(result) == len(names) {
			return result
		}
	}
	return result
}

func buildComponentFile(entries []componentEntry, importAliases map[string]string) (string, error) {
	header := fmt.Sprintf(`// Code generated by dever; DO NOT EDIT.
// Generated at: %s
// Description: 自动注册 active component 的 manifest、页面和前端插件资源。
`, time.Now().Format("2006-01-02 15:04:05"))

	builder := &strings.Builder{}
	builder.WriteString(header)
	builder.WriteString("package load\n\n")

	if len(entries) > 0 {
		builder.WriteString("import (\n")

		importPaths := make([]string, 0, len(importAliases))
		for path := range importAliases {
			importPaths = append(importPaths, path)
		}
		sort.Strings(importPaths)
		for _, path := range importPaths {
			builder.WriteString(fmt.Sprintf("    %s %q\n", importAliases[path], path))
		}
		if len(importPaths) > 0 {
			builder.WriteString("\n")
		}
		builder.WriteString("    component \"github.com/shemic/dever/component\"\n")
		builder.WriteString(")\n\n")
	} else {
		builder.WriteString("\n")
	}
	builder.WriteString("func init() {\n")
	builder.WriteString("    registerComponents()\n")
	builder.WriteString("}\n\n")
	builder.WriteString("// registerComponents 自动注册所有 active component。\n")
	builder.WriteString("func registerComponents() {\n")
	for _, entry := range entries {
		builder.WriteString("    component.Register(component.Definition{\n")
		builder.WriteString(fmt.Sprintf("        Name: %q,\n", entry.Name))
		builder.WriteString(fmt.Sprintf("        Source: %q,\n", entry.Source))
		builder.WriteString(fmt.Sprintf("        ImportPath: %q,\n", entry.ImportPath))
		builder.WriteString(fmt.Sprintf("        DiskDir: %q,\n", entry.DiskDir))
		builder.WriteString(fmt.Sprintf("        ManifestFS: %s.ManifestFS,\n", entry.ImportAlias))
		if entry.PageFS {
			builder.WriteString(fmt.Sprintf("        PageFS: %s.PageFS,\n", entry.ImportAlias))
			builder.WriteString(fmt.Sprintf("        PagePrefix: %q,\n", entry.PagePrefix))
		}
		if entry.FrontFS {
			builder.WriteString(fmt.Sprintf("        FrontFS: %s.FrontFS,\n", entry.ImportAlias))
			builder.WriteString(fmt.Sprintf("        FrontPrefix: %q,\n", entry.FrontPrefix))
		}
		builder.WriteString("    })\n")
	}
	builder.WriteString("}\n")

	formatted, err := format.Source([]byte(builder.String()))
	if err != nil {
		return "", err
	}
	return string(formatted), nil
}
