package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode"

	"github.com/shemic/dever/util"
)

type routeEntry struct {
	path   string
	method string
	line   string
}

// GenerateRoutes 扫描项目 API 目录，生成统一的路由注册文件。
func GenerateRoutes(projectRoot string) error {
	if projectRoot == "" {
		projectRoot = "."
	}
	rootPath, err := filepath.Abs(projectRoot)
	if err != nil {
		return fmt.Errorf("解析项目根目录失败: %w", err)
	}

	output := filepath.Join(rootPath, "data", "router.go")
	moduleName, err := readProjectModuleName(filepath.Join(rootPath, "go.mod"))
	if err != nil {
		return err
	}

	// ✅ 检测 server.Server 方法风格（Get 还是 GET）
	methodStyle := detectServerMethodStyle(filepath.Join(rootPath, "dever", "server"))
	//fmt.Println("✅ 检测到 Server 方法风格:", methodStyle)

	var routes []routeEntry
	importAliases := make(map[string]string)
	aliasUsage := make(map[string]int)
	apiMethodRegexp := regexp.MustCompile(`func\s*\(\s*(?:\w+\s+)?\*?([A-Z]\w*)\s*\)\s*(Get|Post|Put|Delete)([A-Z]\w*)\s*\(`)

	moduleSources, err := util.ListModuleSources(rootPath)
	if err != nil {
		return fmt.Errorf("读取模块目录失败: %w", err)
	}

	for _, source := range moduleSources {
		walkErr := filepath.Walk(source.Root, func(path string, info os.FileInfo, err error) error {
			if err != nil || info.IsDir() {
				return nil
			}
			if !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
				return nil
			}
			if !strings.Contains(path, string(os.PathSeparator)+"api"+string(os.PathSeparator)) {
				return nil
			}

			relPath, err := filepath.Rel(source.Root, path)
			if err != nil {
				return nil
			}

			parts := strings.Split(relPath, string(os.PathSeparator))
			apiIndex := indexOf(parts, "api")
			if apiIndex < 0 || len(parts) < 2 {
				return nil
			}
			module := sanitizePathSegment(source.Name)
			importPath := joinImportPath(source.Import, parts[:len(parts)-1]...)
			alias := ensureAlias(importAliases, aliasUsage, importPath, filepath.Join(source.Name, filepath.Dir(relPath)))

			content, _ := os.ReadFile(path)
			methodMatches := apiMethodRegexp.FindAllStringSubmatch(string(content), -1)
			for _, m := range methodMatches {
				recvType := m[1]
				methodVerb := m[2]
				methodName := m[3]
				method := formatMethodName(methodVerb, methodStyle)
				funcSnake := camelToSnake(methodName)
				resource := camelToSnake(recvType)
				routePath := fmt.Sprintf("/%s/%s/%s", module, resource, funcSnake)
				if module == "main" {
					routePath = fmt.Sprintf("/%s/%s", resource, funcSnake)
				}
				line := fmt.Sprintf(`r.%s("%s", %s.%s{}.%s)`,
					method, routePath, alias, recvType, methodVerb+methodName)
				routes = append(routes, routeEntry{
					path:   routePath,
					method: method,
					line:   line,
				})
			}
			return nil
		})
		if walkErr != nil {
			return walkErr
		}
	}

	sort.Slice(routes, func(i, j int) bool {
		if routes[i].path == routes[j].path {
			return routes[i].method < routes[j].method
		}
		return routes[i].path < routes[j].path
	})

	routeLines := make([]string, len(routes))
	for i, r := range routes {
		routeLines[i] = r.line
	}

	var importLines []string
	if len(importAliases) > 0 {
		importPaths := make([]string, 0, len(importAliases))
		for imp := range importAliases {
			importPaths = append(importPaths, imp)
		}
		sort.Strings(importPaths)
		for _, imp := range importPaths {
			alias := importAliases[imp]
			importLines = append(importLines, fmt.Sprintf(`    %s "%s"`, alias, imp))
		}
	}

	header := fmt.Sprintf(`// Code generated by dever; DO NOT EDIT.
// Generated at: %s
// Description: 自动路由注册文件，扫描 module/*/api/*.go 及其重定向源，根据结构体方法命名生成 HTTP 路由。
// 示例：module/user/api/project.go 或 module/front/main.go 指向的真实目录 -> func (Project) GetList -> GET /user/project/list
//
`, time.Now().Format("2006-01-02 15:04:05"))

	serverImport := "github.com/shemic/dever/server"
	middlewareImport := fmt.Sprintf(`    "%s/middleware"`, moduleName)

	var code string
	var resultMsg string
	if len(routes) == 0 {
		code = fmt.Sprintf(`%spackage data

import (
    "%s"
    "%s/middleware"
)

// RegisterRoutes 自动注册所有模块路由
func RegisterRoutes(r server.Server) {
    middleware.Register()
    // 当前没有可注册的 API 路由
}
`, header, serverImport, moduleName)
		resultMsg = "⚠️ 未检测到路由函数，已生成空的 data/router.go"
	} else {
		bodyLines := make([]string, 0, len(routes)+1)
		bodyLines = append(bodyLines, "middleware.Register()")
		for _, line := range routeLines {
			bodyLines = append(bodyLines, line)
		}
		code = fmt.Sprintf(`%spackage data

import (
    "%s"
    %s
%s
)

// RegisterRoutes 自动注册所有模块路由
func RegisterRoutes(r server.Server) {
%s
}
`, header, serverImport, middlewareImport, strings.Join(importLines, "\n"), "    "+strings.Join(bodyLines, "\n    "))
		resultMsg = "✅ Routes generated successfully → " + output
	}

	os.MkdirAll(filepath.Dir(output), 0755)
	if err := os.WriteFile(output, []byte(code), 0644); err != nil {
		return err
	}

	fmt.Println(resultMsg)
	return nil
}

// ------------------------ 工具函数 ------------------------
func indexOf(parts []string, target string) int {
	for i, p := range parts {
		if p == target {
			return i
		}
	}
	return -1
}

func sanitizePathSegment(s string) string {
	clean := strings.TrimSpace(s)
	if clean == "" {
		return "unnamed"
	}
	clean = strings.ReplaceAll(clean, " ", "_")
	clean = strings.ReplaceAll(clean, "\\", "_")
	clean = strings.ReplaceAll(clean, "-", "_")
	return strings.ToLower(clean)
}

func ensureAlias(aliasMap map[string]string, usage map[string]int, importPath, relDir string) string {
	if alias, ok := aliasMap[importPath]; ok {
		return alias
	}
	base := buildAlias(relDir)
	count := usage[base]
	alias := base
	if count > 0 {
		alias = fmt.Sprintf("%s_%d", base, count)
	}
	usage[base] = count + 1
	aliasMap[importPath] = alias
	return alias
}

func buildAlias(relDir string) string {
	if relDir == "" || relDir == "." {
		return "api_root"
	}
	parts := strings.Split(relDir, string(os.PathSeparator))
	aliasParts := make([]string, 0, len(parts))
	for _, part := range parts {
		if part == "" || part == "." || part == "module" || part == "api" {
			continue
		}
		aliasParts = append(aliasParts, part)
	}
	if len(aliasParts) == 0 {
		aliasParts = append(aliasParts, "api")
	}
	alias := strings.Join(aliasParts, "_")
	return normalizeIdentifier(alias)
}

func normalizeIdentifier(s string) string {
	var b strings.Builder
	lastUnderscore := false
	for i, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9':
			if i == 0 && r >= '0' && r <= '9' {
				b.WriteByte('_')
			}
			b.WriteRune(r)
			lastUnderscore = false
		default:
			if !lastUnderscore {
				b.WriteByte('_')
				lastUnderscore = true
			}
		}
	}
	alias := strings.Trim(b.String(), "_")
	if alias == "" {
		return "api_pkg"
	}
	if alias[0] >= '0' && alias[0] <= '9' {
		alias = "_" + alias
	}
	return strings.ToLower(alias)
}

// 驼峰转下划线
func camelToSnake(s string) string {
	if isAcronymPlural(s) {
		return strings.ToLower(s)
	}
	var result []rune
	runes := []rune(s)
	for i, r := range runes {
		if unicode.IsUpper(r) {
			if i > 0 {
				prev := runes[i-1]
				if unicode.IsLower(prev) || unicode.IsDigit(prev) {
					result = append(result, '_')
				} else if i+1 < len(runes) {
					next := runes[i+1]
					if unicode.IsLower(next) {
						result = append(result, '_')
					}
				}
			}
			r = unicode.ToLower(r)
		}
		result = append(result, r)
	}
	return string(result)
}

func isAcronymPlural(s string) bool {
	runes := []rune(s)
	if len(runes) < 2 {
		return false
	}
	last := runes[len(runes)-1]
	if last != 's' && last != 'S' {
		return false
	}
	for _, r := range runes[:len(runes)-1] {
		if !unicode.IsUpper(r) {
			return false
		}
	}
	return true
}

// 检测 server.Server 方法风格（Get 还是 GET）
func detectServerMethodStyle(serverDir string) string {
	methodStyle := "Title" // 默认 r.Get()
	filepath.Walk(serverDir, func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() {
			return nil
		}
		if !strings.HasSuffix(path, ".go") {
			return nil
		}
		content, _ := os.ReadFile(path)
		if strings.Contains(string(content), "func (") {
			if strings.Contains(string(content), "GET(") {
				methodStyle = "Upper"
			}
		}
		return nil
	})
	return methodStyle
}

func readProjectModuleName(path string) (string, error) {
	content, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	lines := strings.Split(string(content), "\n")
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "module ") {
			return strings.TrimSpace(strings.TrimPrefix(trimmed, "module ")), nil
		}
	}
	return "", fmt.Errorf("无法从 go.mod 读取 module 名，请检查文件")
}

func joinImportPath(root string, parts ...string) string {
	cleanRoot := strings.TrimRight(strings.TrimSpace(root), "/")
	segments := make([]string, 0, len(parts))
	for _, part := range parts {
		trimmed := strings.Trim(filepath.ToSlash(strings.TrimSpace(part)), "/")
		if trimmed == "" || trimmed == "." {
			continue
		}
		segments = append(segments, trimmed)
	}
	if len(segments) == 0 {
		return cleanRoot
	}
	return cleanRoot + "/" + strings.Join(segments, "/")
}

// 格式化方法名（自动匹配 Get vs GET）
func formatMethodName(method, style string) string {
	if style == "Upper" {
		return strings.ToUpper(method)
	}
	return strings.Title(strings.ToLower(method))
}
