package cmd

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode"

	"github.com/shemic/dever/util"
)

type routeEntry struct {
	path   string
	method string
	line   string
}

type middlewareEntry struct {
	importPath string
	line       string
}

// GenerateRoutes 扫描项目 API 目录，生成统一的路由注册文件。
func GenerateRoutes(projectRoot string) error {
	sources, err := LoadProjectSources(projectRoot)
	if err != nil {
		return err
	}
	return GenerateRoutesForSources(sources)
}

func GenerateRoutesForSources(sources ProjectSources) error {
	output := filepath.Join(sources.Root, "data", "router.go")

	// ✅ 检测 server.Server 方法风格（Get 还是 GET）
	methodStyle := detectServerMethodStyle(filepath.Join(sources.Root, "dever", "server"))
	//fmt.Println("✅ 检测到 Server 方法风格:", methodStyle)

	var routes []routeEntry
	importAliases := make(map[string]string)
	aliasUsage := make(map[string]int)
	apiMethodRegexp := regexp.MustCompile(`func\s*\(\s*(?:\w+\s+)?\*?([A-Z]\w*)\s*\)\s*(Get|Post|Put|Delete)([A-Z]\w*)\s*\(`)

	middlewares := discoverMiddlewareEntries(sources.Root, sources.Module, sources.ModuleSources, importAliases, aliasUsage)

	for _, source := range sources.ModuleSources {
		walkErr := walkGoFilesUnder(source, "api", func(file goSourceFile) error {
			parts := strings.Split(file.RelPath, string(os.PathSeparator))
			apiIndex := indexOf(parts, "api")
			if apiIndex < 0 || len(parts) < 2 {
				return nil
			}
			content, err := os.ReadFile(file.FullPath)
			if err != nil {
				return fmt.Errorf("读取 API 文件失败 %s: %w", file.FullPath, err)
			}
			methodMatches := apiMethodRegexp.FindAllStringSubmatch(string(content), -1)
			if len(methodMatches) == 0 {
				return nil
			}
			module := sanitizePathSegment(source.Name)
			importPath := joinImportPath(source.Import, parts[:len(parts)-1]...)
			alias := ensureAlias(importAliases, aliasUsage, importPath, filepath.Join(source.Name, filepath.Dir(file.RelPath)))

			for _, m := range methodMatches {
				recvType := m[1]
				methodVerb := m[2]
				methodName := m[3]
				method := formatMethodName(methodVerb, methodStyle)
				funcSnake := camelToSnake(methodName)
				resource := camelToSnake(recvType)
				routePath := apiRoutePath(module, parts, apiIndex, resource, funcSnake)
				line := fmt.Sprintf(`r.%s("%s", %s.%s{}.%s)`,
					method, routePath, alias, recvType, methodVerb+methodName)
				routes = append(routes, routeEntry{
					path:   routePath,
					method: method,
					line:   line,
				})
			}
			return nil
		})
		if walkErr != nil {
			return walkErr
		}
	}

	sort.Slice(routes, func(i, j int) bool {
		if routes[i].path == routes[j].path {
			return routes[i].method < routes[j].method
		}
		return routes[i].path < routes[j].path
	})

	routeLines := make([]string, len(routes))
	for i, r := range routes {
		routeLines[i] = r.line
	}

	var importLines []string
	if len(importAliases) > 0 {
		importPaths := make([]string, 0, len(importAliases))
		for imp := range importAliases {
			importPaths = append(importPaths, imp)
		}
		sort.Strings(importPaths)
		for _, imp := range importPaths {
			alias := importAliases[imp]
			importLines = append(importLines, fmt.Sprintf(`    %s "%s"`, alias, imp))
		}
	}

	header := fmt.Sprintf(`// Code generated by dever; DO NOT EDIT.
// Generated at: %s
// Description: 自动路由注册文件，扫描 module/package 的 api/**/*.go 及其重定向源，根据结构体方法命名生成 HTTP 路由。
// 示例：package/bot/api/admin/team.go -> func (Team) GetList -> GET /bot/admin/team/list
//
`, time.Now().Format("2006-01-02 15:04:05"))

	serverImport := "github.com/shemic/dever/server"
	deverMiddlewareImport := "github.com/shemic/dever/middleware"
	middlewareLines := []string{"devermiddleware.UseDefault()"}
	for _, entry := range middlewares {
		middlewareLines = append(middlewareLines, entry.line)
	}

	var code string
	bodyLines := make([]string, 0, len(middlewareLines)+len(routes)+1)
	bodyLines = append(bodyLines, middlewareLines...)
	resultMsg := "✅ Routes generated successfully → " + output
	if len(routes) == 0 {
		bodyLines = append(bodyLines, "// 当前没有可注册的 API 路由")
		resultMsg = "⚠️ 未检测到路由函数，已生成空的 data/router.go"
	} else {
		bodyLines = append(bodyLines, routeLines...)
	}
	code = fmt.Sprintf(`%spackage data

import (
    devermiddleware "%s"
    "%s"
%s
)

// RegisterRoutes 自动注册所有模块路由
func RegisterRoutes(r server.Server) {
%s
}
`, header, deverMiddlewareImport, serverImport, formatGeneratedImports(importLines), "    "+strings.Join(bodyLines, "\n    "))

	if err := os.MkdirAll(filepath.Dir(output), 0o755); err != nil {
		return fmt.Errorf("创建路由输出目录失败: %w", err)
	}
	formatted, err := format.Source([]byte(code))
	if err != nil {
		return fmt.Errorf("格式化路由输出失败: %w", err)
	}
	code = string(formatted)
	if err := os.WriteFile(output, []byte(code), 0644); err != nil {
		return err
	}

	fmt.Println(resultMsg)
	return nil
}

// ------------------------ 工具函数 ------------------------
func discoverMiddlewareEntries(rootPath, moduleName string, moduleSources []util.ModuleSource, importAliases map[string]string, aliasUsage map[string]int) []middlewareEntry {
	entries := make([]middlewareEntry, 0)
	seen := make(map[string]struct{})
	add := func(importPath, relDir string) {
		importPath = strings.TrimSpace(importPath)
		if importPath == "" {
			return
		}
		if _, ok := seen[importPath]; ok {
			return
		}
		seen[importPath] = struct{}{}
		alias := ensureAlias(importAliases, aliasUsage, importPath, relDir)
		entries = append(entries, middlewareEntry{
			importPath: importPath,
			line:       alias + ".Register()",
		})
	}

	if middlewarePackageHasRegister(filepath.Join(rootPath, "middleware")) {
		add(joinImportPath(moduleName, "middleware"), "project_middleware")
	}

	for _, source := range moduleSources {
		if !middlewarePackageHasRegister(filepath.Join(source.Root, "middleware")) {
			continue
		}
		add(joinImportPath(source.Import, "middleware"), filepath.Join(source.Name, "middleware"))
	}

	sort.Slice(entries, func(i, j int) bool {
		return entries[i].importPath < entries[j].importPath
	})
	return entries
}

func middlewarePackageHasRegister(dir string) bool {
	files, err := os.ReadDir(dir)
	if err != nil {
		return false
	}
	registerRegexp := regexp.MustCompile(`(?m)^\s*func\s+Register\s*\(`)
	for _, file := range files {
		if file == nil || file.IsDir() {
			continue
		}
		name := file.Name()
		if !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}
		content, err := os.ReadFile(filepath.Join(dir, name))
		if err != nil {
			continue
		}
		if registerRegexp.Match(content) {
			return true
		}
	}
	return false
}

func formatGeneratedImports(importLines []string) string {
	if len(importLines) == 0 {
		return ""
	}
	return strings.Join(importLines, "\n") + "\n"
}

func apiRoutePath(module string, parts []string, apiIndex int, resource string, action string) string {
	segments := make([]string, 0, len(parts)+2)
	if module != "main" {
		segments = append(segments, module)
	}
	for _, part := range parts[apiIndex+1 : len(parts)-1] {
		if segment := sanitizePathSegment(part); segment != "" {
			segments = append(segments, segment)
		}
	}
	segments = append(segments, resource, action)
	return "/" + strings.Join(segments, "/")
}

func indexOf(parts []string, target string) int {
	for i, p := range parts {
		if p == target {
			return i
		}
	}
	return -1
}

func sanitizePathSegment(s string) string {
	clean := strings.TrimSpace(s)
	if clean == "" {
		return "unnamed"
	}
	clean = strings.ReplaceAll(clean, " ", "_")
	clean = strings.ReplaceAll(clean, "\\", "_")
	clean = strings.ReplaceAll(clean, "-", "_")
	return strings.ToLower(clean)
}

func ensureAlias(aliasMap map[string]string, usage map[string]int, importPath, relDir string) string {
	if alias, ok := aliasMap[importPath]; ok {
		return alias
	}
	base := buildAlias(relDir)
	count := usage[base]
	alias := base
	if count > 0 {
		alias = fmt.Sprintf("%s_%d", base, count)
	}
	usage[base] = count + 1
	aliasMap[importPath] = alias
	return alias
}

func buildAlias(relDir string) string {
	if relDir == "" || relDir == "." {
		return "api_root"
	}
	parts := strings.Split(relDir, string(os.PathSeparator))
	aliasParts := make([]string, 0, len(parts))
	for _, part := range parts {
		if part == "" || part == "." || part == "module" || part == "api" {
			continue
		}
		aliasParts = append(aliasParts, part)
	}
	if len(aliasParts) == 0 {
		aliasParts = append(aliasParts, "api")
	}
	alias := strings.Join(aliasParts, "_")
	return normalizeIdentifier(alias)
}

func normalizeIdentifier(s string) string {
	var b strings.Builder
	lastUnderscore := false
	for i, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9':
			if i == 0 && r >= '0' && r <= '9' {
				b.WriteByte('_')
			}
			b.WriteRune(r)
			lastUnderscore = false
		default:
			if !lastUnderscore {
				b.WriteByte('_')
				lastUnderscore = true
			}
		}
	}
	alias := strings.Trim(b.String(), "_")
	if alias == "" {
		return "api_pkg"
	}
	if alias[0] >= '0' && alias[0] <= '9' {
		alias = "_" + alias
	}
	return strings.ToLower(alias)
}

// 驼峰转下划线
func camelToSnake(s string) string {
	if isAcronymPlural(s) {
		return strings.ToLower(s)
	}
	var result []rune
	runes := []rune(s)
	for i, r := range runes {
		if unicode.IsUpper(r) {
			if i > 0 {
				prev := runes[i-1]
				if unicode.IsLower(prev) || unicode.IsDigit(prev) {
					result = append(result, '_')
				} else if i+1 < len(runes) {
					next := runes[i+1]
					if unicode.IsLower(next) {
						result = append(result, '_')
					}
				}
			}
			r = unicode.ToLower(r)
		}
		result = append(result, r)
	}
	return string(result)
}

func isAcronymPlural(s string) bool {
	runes := []rune(s)
	if len(runes) < 2 {
		return false
	}
	last := runes[len(runes)-1]
	if last != 's' && last != 'S' {
		return false
	}
	for _, r := range runes[:len(runes)-1] {
		if !unicode.IsUpper(r) {
			return false
		}
	}
	return true
}

// 检测 server.Server 方法风格（Get 还是 GET）
func detectServerMethodStyle(serverDir string) string {
	methodStyle := "Title" // 默认 r.Get()
	_ = filepath.Walk(serverDir, func(path string, info os.FileInfo, err error) error {
		if err != nil || info == nil || info.IsDir() {
			return nil
		}
		if !strings.HasSuffix(path, ".go") {
			return nil
		}
		content, readErr := os.ReadFile(path)
		if readErr != nil {
			return nil
		}
		if strings.Contains(string(content), "func (") {
			if strings.Contains(string(content), "GET(") {
				methodStyle = "Upper"
			}
		}
		return nil
	})
	return methodStyle
}

func joinImportPath(root string, parts ...string) string {
	cleanRoot := strings.TrimRight(strings.TrimSpace(root), "/")
	segments := make([]string, 0, len(parts))
	for _, part := range parts {
		trimmed := strings.Trim(filepath.ToSlash(strings.TrimSpace(part)), "/")
		if trimmed == "" || trimmed == "." {
			continue
		}
		segments = append(segments, trimmed)
	}
	if len(segments) == 0 {
		return cleanRoot
	}
	return cleanRoot + "/" + strings.Join(segments, "/")
}

// 格式化方法名（自动匹配 Get vs GET）
func formatMethodName(method, style string) string {
	if style == "Upper" {
		return strings.ToUpper(method)
	}
	return strings.Title(strings.ToLower(method))
}
